version: "3.7"

networks:
  soa_network:
    name: soa_network
    driver: bridge

volumes:
  soa_pg:
    driver: local
  soa_cache:
    driver: local

services:
  soa-svc:
    image: golang:1.23-alpine
    container_name: soa-svc
    volumes:
      - ./:/home/go/src
      - ./go.sh:/home/go/go.sh
    entrypoint: [ "sh", "-c", "chmod 777 /home/go/go.sh && sh /home/go/go.sh && tail -f /dev/null" ]
    environment:
      GO111MODULE: "on"
      SERVICE_NAME: soa-svc
    working_dir: /home/go/src
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - soa_network

  soa_pg:
    container_name: soa_pg
    image: postgres:14.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: soa
      PGDATA: /data/postgres
    volumes:
      - soa_pg:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - soa_network

  soa_redis_server:
    image: redis
    container_name: soa_redis_server
    ports:
      - "6379:6379"
    networks:
      - soa_network
    volumes:
      - ./redis-data:/data

  soa_redis_commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=soa_redis_server
    networks:
      - soa_network
    depends_on:
      - soa_redis_server